---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
unzip("activity.zip")
dataset <- read.csv("activity.csv")
dataset$date <- as.Date(dataset$date, format="%Y-%m-%d")
```



## What is mean total number of steps taken per day?
```{r}
library("plyr")
total_steps_per_day <- ddply(dataset, .(date), summarize, sum(steps))
names(total_steps_per_day) <- c("date", "steps")
hist(total_steps_per_day$steps,
     main = "Histogram of total steps per day",
     xlab = "steps per day")
mean(total_steps_per_day$steps, na.rm = TRUE)
median(total_steps_per_day$steps, na.rm = TRUE)
```


## What is the average daily activity pattern?
```{r}
average_steps_across_intervals <- ddply(dataset, .(interval), summarize, mean(steps, na.rm = TRUE))
names(average_steps_across_intervals) <- c("interval", "average_steps")
plot(average_steps_across_intervals$interval,
     average_steps_across_intervals$average_steps,
     type = "l",
     main = "Average steps taken across all days",
     xlab = "5-minute interval",
     ylab = "average steps taken")

# Calculate 5-minute interval with maximum number of average steps
max_average_location <- which.max(average_steps_across_intervals$average_steps)
average_steps_across_intervals$interval[max_average_location]
```



## Imputing missing values
```{r}
# Total number of missing values
sum(is.na(dataset$steps))
```

## Are there differences in activity patterns between weekdays and weekends?
